export const themes = {
  "vs-dark": {
    label: "Dark",
    pageBg: "theme-page",
    chatBg: "theme-surface",
    boardBg: "theme-card",
    panel: "theme-panel",
    border: "border-[var(--border-color)]",
    input: "theme-input",
    heading: "theme-text",
    muted: "theme-muted",
    primaryBtn: "bg-gradient-to-r from-blue-600 to-cyan-500 text-white",
    accentText: "text-blue-400",
  },
  "vs-light": {
    label: "Light",
    pageBg: "theme-page",
    chatBg: "theme-surface",
    boardBg: "theme-card",
    panel: "theme-panel",
    border: "border-[var(--border-color)]",
    input: "theme-input",
    heading: "theme-text",
    muted: "theme-muted",
    primaryBtn: "bg-gradient-to-r from-sky-500 to-indigo-500 text-white",
    accentText: "text-indigo-500",
  },
  "ai-theme": {
    label: "Moderate",
    pageBg: "theme-page",
    chatBg: "theme-surface",
    boardBg: "theme-card",
    panel: "theme-panel",
    border: "border-[var(--border-color)]",
    input: "theme-input",
    heading: "theme-text",
    muted: "theme-muted",
    primaryBtn: "bg-gradient-to-r from-amber-600 to-teal-600 text-white",
    accentText: "text-amber-700",
  },
};
